import time
import os
from pynput.keyboard import Controller, Key

# --- Configuration ---
# The full path to the log file generated by the game.
LOG_FILE_PATH = r"C:\Program Files (x86)\Steam\steamapps\common\Puck\Logs\AnnouncerMod.log"
# The prefix used in the C# mod's Debug.Log statement for commentary.
COMMENTARY_PREFIX = "BROADCAST: "

# Initialize the keyboard controller to simulate key presses.
keyboard = Controller()

def follow_log_file(file_path):
    """
    A generator function that yields new lines added to a file.
    This behaves like the 'tail -f' command.
    """
    if not os.path.exists(file_path):
        print(f"Error: Log file not found at '{file_path}'")
        print("Please ensure the path is correct and the game has been run at least once.")
        return

    print(f"Watching for new commentary in: {file_path}")
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
        # Seek to the end of the file to only read new lines.
        file.seek(0, 2)
        while True:
            line = file.readline()
            if not line:
                # No new line, wait a moment before checking again.
                time.sleep(0.1)
                continue
            yield line

def type_commentary_in_game(message):
    """
    Simulates keyboard presses to open chat, type a message, and send it.
    """
    print(f"Broadcasting: '{message}'")
    try:
        # 1. Press 't' to open the in-game chat window.
        keyboard.press('t')
        keyboard.release('t')
        # Increased delay to ensure the chat box is open and has processed the initial 't'
        time.sleep(0.2) 

        # 2. Press backspace to delete the 't' that opened the chat.
        keyboard.press(Key.backspace)
        keyboard.release(Key.backspace)
        time.sleep(0.05)

        # 3. Type the message directly instead of pasting to avoid clipboard issues.
        keyboard.type(message)
        time.sleep(0.1)

        # 4. Press 'Enter' to send the message.
        keyboard.press(Key.enter)
        keyboard.release(Key.enter)
        
    except Exception as e:
        print(f"An error occurred while trying to type: {e}")

def main():
    """
    Main function to monitor the log and trigger the typing.
    """
    log_lines = follow_log_file(LOG_FILE_PATH)
    if not log_lines:
        return # Stop if the log file wasn't found.
        
    for line in log_lines:
        # Check if the new line is a commentary line from the mod.
        if COMMENTARY_PREFIX in line:
            # Extract the actual commentary message by removing the prefix and any extra whitespace.
            commentary_message = line.split(COMMENTARY_PREFIX, 1)[1].strip()
            
            # Ensure the game window is active before typing.
            # A short delay gives you time to switch back to the game.
            print("New commentary detected! Tabbing back into the game...")
            time.sleep(2) # 2-second window to focus the game.
            
            type_commentary_in_game(commentary_message)

if __name__ == "__main__":
    main()

