// --- Step 1: Add necessary using statements ---
using UnityEngine;
using HarmonyLib;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using Unity.Collections; // Required for FixedString types
using Unity.Netcode; // Required for network client checks

// --- Step 2: Define your mod's namespace and main class ---
namespace AnnouncerMod
{
    /// <summary>
    /// A simple static logger to write AnnouncerMod specific messages to its own file.
    /// </summary>
    internal static class AnnouncerLogger
    {
        private static StreamWriter logWriter;

        static AnnouncerLogger()
        {
            try
            {
                string puckGamePath = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
                string logDirectory = Path.Combine(puckGamePath, "Logs");

                if (!Directory.Exists(logDirectory))
                {
                    Directory.CreateDirectory(logDirectory);
                }

                string logFilePath = Path.Combine(logDirectory, "AnnouncerMod.log");
                // Set append to false to overwrite the log file on each startup
                logWriter = new StreamWriter(logFilePath, false) { AutoFlush = true };
                Log("Logger initialized successfully.");
            }
            catch (Exception e)
            {
                Debug.LogError($"[AnnouncerMod] Failed to initialize file logger: {e.Message}");
                logWriter = null;
            }
        }

        public static void Log(string message)
        {
            Debug.Log($"[AnnouncerMod] {message}");
            logWriter?.WriteLine($"[{DateTime.Now:yyyy-MM-dd HH:mm:ss}] {message}");
        }

        public static void Close()
        {
            logWriter?.Close();
            logWriter = null;
        }
    }

    /// <summary>
    /// Monitors the Puck.log file for stat changes from the server-side stats mod.
    /// This provides a more reliable way to detect events like shots, saves, and blocks.
    /// </summary>
    internal static class LogFileMonitor
    {
        // Action to be invoked when a stat is found in the log file.
        public static event Action<string, ulong, string> OnStatFound;
        
        private static long lastPosition = 0;
        private static string logFilePath;
        
        // Regex to parse the specific log entries generated by the server-side stats mod.
        private static readonly Regex statRegex = new Regex(@"oomtm450_stats(SOG|SAVEPERC|BLOCK|TAKEAWAY|TURNOVER|PASS)(\d{17}).*Content : (.*)$", RegexOptions.Compiled);
        private static Timer fileCheckTimer;

        public static void Initialize()
        {
            try
            {
                string puckGamePath = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
                logFilePath = Path.Combine(puckGamePath, "Logs", "Puck.log");

                if (!File.Exists(logFilePath))
                {
                    AnnouncerLogger.Log($"Puck.log not found at {logFilePath}. Log monitoring will not start.");
                    return;
                }
                
                // Read to the end of the file on start to avoid processing old logs
                using (var fs = new FileStream(logFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                {
                    lastPosition = fs.Length;
                }

                // FileSystemWatcher can be unreliable on some systems, so we use a timer to periodically check.
                fileCheckTimer = new Timer(CheckForLogChanges, null, 0, 250); // Check every 250ms

                AnnouncerLogger.Log("LogFileMonitor initialized and watching Puck.log.");
            }
            catch (Exception e)
            {
                AnnouncerLogger.Log($"Failed to initialize LogFileMonitor: {e.Message}");
            }
        }
        
        private static void CheckForLogChanges(object state)
        {
            try
            {
                if (!File.Exists(logFilePath)) return;

                long currentLength = new FileInfo(logFilePath).Length;
                if (currentLength > lastPosition)
                {
                    ReadNewLogEntries();
                }
                else if (currentLength < lastPosition)
                {
                    // Log file was likely reset
                    lastPosition = 0;
                }
            }
            catch (Exception e)
            {
                AnnouncerLogger.Log($"Error checking Puck.log for changes: {e.Message}");
            }
        }

        private static void ReadNewLogEntries()
        {
            try
            {
                using (var fs = new FileStream(logFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                {
                    fs.Seek(lastPosition, SeekOrigin.Begin);
                    using (var reader = new StreamReader(fs))
                    {
                        string line;
                        while ((line = reader.ReadLine()) != null)
                        {
                            ParseLine(line);
                        }
                        lastPosition = fs.Position;
                    }
                }
            }
            catch (Exception e)
            {
                AnnouncerLogger.Log($"Error reading Puck.log: {e.Message}");
            }
        }

        private static void ParseLine(string line)
        {
            Match match = statRegex.Match(line);
            if (match.Success)
            {
                string statType = match.Groups[1].Value;
                if (ulong.TryParse(match.Groups[2].Value, out ulong playerId))
                {
                    string content = match.Groups[3].Value.Trim();
                    AnnouncerLogger.Log($"[LogMonitor] Found Stat: Type={statType}, PlayerID={playerId}, Content={content}");
                    OnStatFound?.Invoke(statType, playerId, content);
                }
            }
        }

        public static void Stop()
        {
            fileCheckTimer?.Dispose();
            fileCheckTimer = null;
            AnnouncerLogger.Log("LogFileMonitor stopped.");
        }
    }

    /// <summary>
    /// Component attached to the puck to determine if it's heading towards a net.
    /// </summary>
    internal class PuckTargetingSystem : MonoBehaviour
    {
        private readonly float MAX_DISTANCE = 50f;
        private readonly LayerMask _goalTriggerLayerMask = LayerMask.GetMask("Goal Trigger");
        private readonly float PUCK_RADIUS_OFFSET = 0.06f;
        private readonly Vector3 TOP_RAY_OFFSET = new Vector3(0, 0.08f, 0);
        private readonly Vector3 BOTTOM_RAY_OFFSET = new Vector3(0, 0.01f, 0);

        internal bool IsHeadedTowardsOpponentNet(Vector3 direction, PlayerTeam shooterTeam)
        {
            if (direction == Vector3.zero) return false;

            Vector3 currentPosition = transform.position;
            Vector3 leftVector = currentPosition + (Quaternion.Euler(0, -90, 0) * direction * PUCK_RADIUS_OFFSET);
            Vector3 rightVector = currentPosition + (Quaternion.Euler(0, 90, 0) * direction * PUCK_RADIUS_OFFSET);

            RaycastHit hit;

            bool hitDetected =
                Physics.Raycast(new Ray(leftVector + TOP_RAY_OFFSET, direction), out hit, MAX_DISTANCE, _goalTriggerLayerMask, QueryTriggerInteraction.Collide) ||
                Physics.Raycast(new Ray(rightVector + TOP_RAY_OFFSET, direction), out hit, MAX_DISTANCE, _goalTriggerLayerMask, QueryTriggerInteraction.Collide) ||
                Physics.Raycast(new Ray(leftVector + BOTTOM_RAY_OFFSET, direction), out hit, MAX_DISTANCE, _goalTriggerLayerMask, QueryTriggerInteraction.Collide) ||
                Physics.Raycast(new Ray(rightVector + BOTTOM_RAY_OFFSET, direction), out hit, MAX_DISTANCE, _goalTriggerLayerMask, QueryTriggerInteraction.Collide);

            if (hitDetected)
            {
                GoalTrigger goalTrigger = hit.collider.GetComponent<GoalTrigger>();
                if (goalTrigger != null)
                {
                    var goalField = AccessTools.Field(typeof(GoalTrigger), "goal");
                    if (goalField != null)
                    {
                        Goal goalObject = (Goal)goalField.GetValue(goalTrigger);
                        if (goalObject != null)
                        {
                            var goalTeamField = AccessTools.Field(typeof(Goal), "Team");
                            if (goalTeamField != null)
                            {
                                PlayerTeam team = (PlayerTeam)goalTeamField.GetValue(goalObject);
                                return team != shooterTeam;
                            }
                        }
                    }
                }
            }
            return false;
        }
    }


    public class Announcer : IPuckMod
    {
        private static readonly Harmony harmony = new Harmony("com.yourname.announcermod");
        private static readonly System.Random random = new System.Random();

        // Enum for commentary event priorities
        private enum CommentaryPriority { Low, Medium, High }
        
        // Class to hold event data for the commentary queue
        private class CommentaryEvent
        {
            public string Message { get; }
            public CommentaryPriority Priority { get; }

            public CommentaryEvent(string message, CommentaryPriority priority)
            {
                Message = message;
                Priority = priority;
            }
        }

        // --- CONFIGURATION & DEBUG SWITCHES ---
        private static readonly bool BroadcastToChat = false;
        private static readonly bool EnableDetailedDebugLogging = false;

        // --- File Paths ---
        private static readonly string gameFilesPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), "Steam", "steamapps", "common", "Puck", "textfiles");
        private static readonly string goalScorerFile = Path.Combine(gameFilesPath, "goal_scorer.txt");
        private static readonly string assistPlayerFile = Path.Combine(gameFilesPath, "goal_assister.txt");
        private static readonly string secondAssistPlayerFile = Path.Combine(gameFilesPath, "goal_assister2.txt");

        // --- VOCABULARY EXPANSION ---
        private static readonly List<string> possessionPhrases = new List<string> { "{0} has it.", "{0} with the puck.", "{0} controls it.", "Here's {0}.", "{0} picks it up.", "{0}.", "{0} for {1}." };
        private static readonly List<string> zoneEntryPhrases = new List<string> { "carries it over the {1}", "brings it across the {1}", "gains the {1}" };
        private static readonly List<string> shotPhrases = new List<string> { "{0} shoots!", "{0} fires!", "A shot from {0}!", "Lets one go!" };
        private static readonly List<string> wideShotPhrases = new List<string> { "{0} shoots wide.", "That one's off the mark.", "{0} misses the net." };
        private static readonly List<string> savePhrases = new List<string> { "Great save by {0}!", "Turned aside by {0}!", "{0} makes the stop!", "Denied by {0}!", "Kicked out by {0}." };
        private static readonly List<string> passPhrases = new List<string> { "{0} to {1}!", "{0} passes to {1}!", "{0} finds {1}.", "{0} over to {1}." };
        private static readonly List<string> boardBattlePhrases = new List<string> { "Battle along the boards!", "Tied up on the boards.", "Pinned against the wall." };
        private static readonly List<string> blockedShotPhrases = new List<string> { "Blocked by {0}!", "Shot blocked!", "{0} gets in the lane!" };
        private static readonly List<string> defensiveZoneClearPhrases = new List<string> { "{0} clears the zone.", "{0} gets it out of the zone." };

        // --- State Tracking Variables ---
        internal static Player lastPlayerWithPuck = null;
        internal static int lastAnnouncedPlayerId = -1;
        internal static float lastPossessionChangeTime = 0f;
        internal static float possessionStartTime = 0f;
        internal static Vector3 lastPuckPosition;
        internal static PlayerTeam lastPlayerWithPuckTeam = PlayerTeam.None;
        internal static Goal redGoal, blueGoal;
        internal static GameState lastKnownGameState;
        internal static bool isFirstCheck = true;
        internal static PuckTargetingSystem puckTargetingSystem;
        internal static Dictionary<int, float> lastPuckTouchTime = new Dictionary<int, float>();
        internal static bool wasPuckFreeInLastFrame = true;
        internal static bool isRedTeamInPositiveZ = true;
        internal static bool isOrientationSet = false;
        internal static bool isPuckTravelingAfterShot = false;
        internal static bool isOffNetShot = false;
        internal static bool isWaitingForFaceoffWin = false;
        internal static Player potentialShooter;
        internal static Player potentialSaver;
        internal static float shotTime;
        internal static bool hasMadeAnnouncementThisPossession = false;
        internal static bool isAnnouncingBoardBattle = false;
        internal static float boardBattleStartTime = 0f;
        private static bool useLogFileDetection = false;
        internal static bool isDetectionMethodSet = false;
        private static readonly Queue<Action> mainThreadActions = new Queue<Action>();
        private static readonly Queue<CommentaryEvent> commentaryQueue = new Queue<CommentaryEvent>();
        private static string lastBroadcastMessage = "";
        private static Dictionary<ulong, int> lastSogCounts = new Dictionary<ulong, int>();
        private static Dictionary<ulong, int> lastBlockCounts = new Dictionary<ulong, int>();
        private static Dictionary<ulong, int> lastSaveCounts = new Dictionary<ulong, int>();
        private static Dictionary<ulong, int> lastPassCounts = new Dictionary<ulong, int>();

        // --- Thresholds and Timings ---
        private const float shotSpeedThreshold = 18f;
        private const float directTakeawayTime = 0.3f;
        private const float interceptionTimeWindow = 1.5f;
        private const float minPossessionTimeForAnnouncement = 5.0f; // Only announce possession after 5 seconds of control
        private const float maxTippedMilliseconds = 150f;
        private const float boardBattleTimeThreshold = 2.0f;
        private const float saveCheckDelay = 0.75f;

        // --- Commentary Cooldown System ---
        private static float commentaryCooldown = 0f;
        private static CommentaryPriority lastBroadcastPriority = CommentaryPriority.Low;
        private static readonly Dictionary<CommentaryPriority, float> CooldownDurations = new Dictionary<CommentaryPriority, float>
        {
            { CommentaryPriority.Low, 1.5f },
            { CommentaryPriority.Medium, 2.5f },
            { CommentaryPriority.High, 4.0f }
        };

        public bool OnEnable()
        {
            try
            {
                harmony.PatchAll(typeof(Announcer).Assembly);
                isFirstCheck = true;
                AnnouncerLogger.Log("AnnouncerMod Enabled and Patches Applied!");
            }
            catch (Exception e) { AnnouncerLogger.Log($"AnnouncerMod failed to patch: {e}"); return false; }
            return true;
        }

        public bool OnDisable()
        {
            try
            {
                harmony.UnpatchSelf();

                if (useLogFileDetection)
                {
                    LogFileMonitor.OnStatFound -= HandleStatFound;
                    LogFileMonitor.Stop();
                    useLogFileDetection = false;
                }
                isDetectionMethodSet = false;

                AnnouncerLogger.Log("AnnouncerMod Disabled and Patches Reverted.");
                AnnouncerLogger.Close();
            }
            catch (Exception e) { AnnouncerLogger.Log($"AnnouncerMod failed to unpatch: {e.Message}"); return false; }
            return true;
        }

        private static void HandleStatFound(string statType, ulong playerId, string content)
        {
            // Enqueue the main logic to be run on the main game thread for thread safety.
            lock (mainThreadActions)
            {
                mainThreadActions.Enqueue(() =>
                {
                    Player player = GetPlayerBySteamId(playerId);
                    if (player == null)
                    {
                        if (EnableDetailedDebugLogging) AnnouncerLogger.Log($"[LogMonitor] Player with SteamID {playerId} not found.");
                        return;
                    }

                    string comment = null;
                    CommentaryPriority priority = CommentaryPriority.Medium;

                    switch (statType)
                    {
                        case "SOG":
                            if(int.TryParse(content, out int newSogCount))
                            {
                                int lastCount = lastSogCounts.ContainsKey(playerId) ? lastSogCounts[playerId] : 0;
                                if(newSogCount > lastCount)
                                {
                                    lastSogCounts[playerId] = newSogCount;
                                    comment = string.Format(shotPhrases[random.Next(shotPhrases.Count)], GetPlayerDisplayName(player));
                                    priority = CommentaryPriority.Medium;
                                }
                            }
                            break;
                        case "BLOCK":
                             if(int.TryParse(content, out int newBlockCount))
                            {
                                int lastCount = lastBlockCounts.ContainsKey(playerId) ? lastBlockCounts[playerId] : 0;
                                if(newBlockCount > lastCount)
                                {
                                    lastBlockCounts[playerId] = newBlockCount;
                                    comment = string.Format(blockedShotPhrases[random.Next(blockedShotPhrases.Count)], GetPlayerDisplayName(player));
                                    priority = CommentaryPriority.Medium;
                                }
                            }
                            break;
                        case "PASS":
                             if(int.TryParse(content, out int newPassCount))
                            {
                                int lastCount = lastPassCounts.ContainsKey(playerId) ? lastPassCounts[playerId] : 0;
                                if(newPassCount > lastCount)
                                {
                                    // We let the physics-based detection handle passes for now to get the receiver's name.
                                    lastPassCounts[playerId] = newPassCount;
                                }
                            }
                            break;
                        case "SAVEPERC":
                            var match = Regex.Match(content, @"\((\d+), \d+\)");
                            if(match.Success && int.TryParse(match.Groups[1].Value, out int newSaveCount))
                            {
                                int lastCount = lastSaveCounts.ContainsKey(playerId) ? lastSaveCounts[playerId] : 0;
                                if(newSaveCount > lastCount && player.Role.Value == PlayerRole.Goalie)
                                {
                                    lastSaveCounts[playerId] = newSaveCount;
                                    comment = string.Format(savePhrases[random.Next(savePhrases.Count)], GetPlayerDisplayName(player));
                                    priority = CommentaryPriority.High;
                                }
                            }
                            break;
                    }

                    if (comment != null)
                    {
                        EnqueueCommentary(comment, priority);
                    }
                });
            }
        }

        private static Player GetPlayerBySteamId(ulong steamId)
        {
            if (NetworkBehaviourSingleton<PlayerManager>.Instance != null)
            {
                return NetworkBehaviourSingleton<PlayerManager>.Instance.GetPlayerBySteamId(steamId.ToString());
            }
            return null; // Fallback if PlayerManager is not available
        }

        private static void InitializeRinkOrientation()
        {
            Goal[] goals = UnityEngine.Object.FindObjectsByType<Goal>(FindObjectsSortMode.None);
            if (goals == null || goals.Length < 2) return;

            var teamField = AccessTools.Field(typeof(Goal), "Team");
            if (teamField == null) { AnnouncerLogger.Log("Error: Could not access 'Team' field in Goal class."); return; }

            foreach (Goal goal in goals)
            {
                PlayerTeam team = (PlayerTeam)teamField.GetValue(goal);
                if (team == PlayerTeam.Red)
                {
                    redGoal = goal;
                    isRedTeamInPositiveZ = goal.transform.position.z > 0;
                }
                else if (team == PlayerTeam.Blue) { blueGoal = goal; }
            }

            if (redGoal != null && blueGoal != null)
            {
                isOrientationSet = true;
                AnnouncerLogger.Log($"Rink orientation set: Red Team is in Positive Z: {isRedTeamInPositiveZ}. Red Goal Z: {redGoal.transform.position.z}, Blue Goal Z: {blueGoal.transform.position.z}");
            }
        }

        private static string GetPlayerDisplayName(Player player)
        {
            if (player == null) return "a player";
            return player.Username.Value.ToString();
        }

        private static string GetZoneFromZ(float z_pos)
        {
            if (Mathf.Abs(z_pos) < 25.0f) return "Neutral";
            if (z_pos > 0) return isRedTeamInPositiveZ ? "Red" : "Blue";
            return isRedTeamInPositiveZ ? "Blue" : "Red";
        }

        private static string GetTeamZoneName(PlayerTeam team)
        {
            if (!isOrientationSet) return "Neutral";
            if (redGoal == null || blueGoal == null) return "Neutral";
            if (team == PlayerTeam.Red) return GetZoneFromZ(redGoal.transform.position.z);
            if (team == PlayerTeam.Blue) return GetZoneFromZ(blueGoal.transform.position.z);
            return "Neutral";
        }
        
        private static void EnqueueCommentary(string message, CommentaryPriority priority)
        {
            if (string.IsNullOrEmpty(message)) return;
            lock(commentaryQueue)
            {
                commentaryQueue.Enqueue(new CommentaryEvent(message, priority));
            }
        }

        internal static void RunCommentary(Puck puck)
        {
            if (puck == null || GameManager.Instance?.GameState == null || puckTargetingSystem == null) return;
            if (GameManager.Instance.GameState.Value.Phase != GamePhase.Playing) { return; }
            if (!isOrientationSet) InitializeRinkOrientation();

            var collisions = puck.GetPlayerCollisions();
            Player playerWithPuck = collisions?.LastOrDefault(c => c.Key != null && c.Key.Role.Value != PlayerRole.Goalie).Key;

            string comment = null;
            CommentaryPriority priority = CommentaryPriority.Low;
            
            if (!useLogFileDetection)
            {
                if (puck.ShotSpeed > shotSpeedThreshold && !isPuckTravelingAfterShot && lastPlayerWithPuck != null)
                {
                    Vector3 shotDirection = puck.Rigidbody.linearVelocity.normalized;
                    bool headedTowardsNet = puckTargetingSystem.IsHeadedTowardsOpponentNet(shotDirection, lastPlayerWithPuck.Team.Value);

                    if (headedTowardsNet)
                    {
                        comment = string.Format(shotPhrases[random.Next(shotPhrases.Count)], GetPlayerDisplayName(lastPlayerWithPuck));
                        EnqueueCommentary(comment, CommentaryPriority.Medium);
                        isPuckTravelingAfterShot = true;
                        isOffNetShot = false;
                        potentialShooter = lastPlayerWithPuck;
                        shotTime = Time.time;
                    }
                    else
                    {
                        isPuckTravelingAfterShot = true;
                        isOffNetShot = true;
                        potentialShooter = lastPlayerWithPuck;
                        shotTime = Time.time;
                    }

                    try
                    {
                        var shotSpeedField = AccessTools.Field(typeof(Puck), "<ShotSpeed>k__BackingField");
                        if (shotSpeedField != null) shotSpeedField.SetValue(puck, 0f);
                    }
                    catch (Exception e) { AnnouncerLogger.Log($"Error resetting ShotSpeed: {e.Message}"); }
                }
            }

            int currentPlayerId = playerWithPuck != null ? playerWithPuck.GetInstanceID() : -1;
            int lastPlayerId = lastPlayerWithPuck != null ? lastPlayerWithPuck.GetInstanceID() : -1;

            if (isWaitingForFaceoffWin && playerWithPuck != null)
            {
                comment = $"{GetPlayerDisplayName(playerWithPuck)} wins the draw!";
                EnqueueCommentary(comment, CommentaryPriority.Medium);
                isWaitingForFaceoffWin = false;
            }
            else if (isPuckTravelingAfterShot && !useLogFileDetection)
            {
                var goalieCollision = collisions?.LastOrDefault(c => c.Key != null && c.Key.Role.Value == PlayerRole.Goalie);
                if (goalieCollision.Value.Key != null && potentialSaver == null)
                {
                    potentialSaver = goalieCollision.Value.Key;
                }
                else
                {
                    var playerCollision = collisions?.LastOrDefault(c => c.Key != null && c.Key.Role.Value != PlayerRole.Goalie);
                    if (playerCollision.Value.Key != null && potentialShooter != null && playerCollision.Value.Key.Team.Value != potentialShooter.Team.Value)
                    {
                        comment = string.Format(blockedShotPhrases[random.Next(blockedShotPhrases.Count)], GetPlayerDisplayName(playerCollision.Value.Key));
                        EnqueueCommentary(comment, CommentaryPriority.Medium);
                        ResetShotState();
                    }
                }

                if (comment == null && Time.time - shotTime > saveCheckDelay)
                {
                    if (potentialSaver != null)
                    {
                        comment = string.Format(savePhrases[random.Next(savePhrases.Count)], GetPlayerDisplayName(potentialSaver));
                        EnqueueCommentary(comment, CommentaryPriority.High);
                        ResetShotState();
                    }
                    else if (isOffNetShot)
                    {
                        comment = string.Format(wideShotPhrases[random.Next(wideShotPhrases.Count)], GetPlayerDisplayName(potentialShooter));
                        EnqueueCommentary(comment, CommentaryPriority.Medium);
                        ResetShotState();
                    }
                }

                if (puck.PredictedSpeed < shotSpeedThreshold / 2) ResetShotState();
            }
            else if (playerWithPuck == null && !wasPuckFreeInLastFrame) { /* Puck became free */ }
            else if (playerWithPuck != null && wasPuckFreeInLastFrame)
            {
                bool isPass = lastPlayerWithPuck != null && playerWithPuck.Team.Value == lastPlayerWithPuck.Team.Value && playerWithPuck.GetInstanceID() != lastPlayerWithPuck.GetInstanceID();

                if (isPass)
                {
                    comment = string.Format(passPhrases[random.Next(passPhrases.Count)], GetPlayerDisplayName(lastPlayerWithPuck), GetPlayerDisplayName(playerWithPuck));
                    EnqueueCommentary(comment, CommentaryPriority.Low);
                }
            }
            else if (playerWithPuck != null && !wasPuckFreeInLastFrame && currentPlayerId != lastPlayerId)
            {
                if (playerWithPuck.Team.Value == lastPlayerWithPuck.Team.Value)
                {
                    comment = string.Format(passPhrases[random.Next(passPhrases.Count)], GetPlayerDisplayName(lastPlayerWithPuck), GetPlayerDisplayName(playerWithPuck));
                    EnqueueCommentary(comment, CommentaryPriority.Low);
                }
            }
            else if (playerWithPuck != null && currentPlayerId == lastPlayerId)
            {
                string currentZone = GetZoneFromZ(puck.transform.position.z);
                string previousZone = GetZoneFromZ(lastPuckPosition.z);
                
                if (currentZone != previousZone && !hasMadeAnnouncementThisPossession)
                {
                    string defensiveZone = GetTeamZoneName(playerWithPuck.Team.Value);

                    if (previousZone == defensiveZone && currentZone == "Neutral")
                    {
                        comment = string.Format(defensiveZoneClearPhrases[random.Next(defensiveZoneClearPhrases.Count)], GetPlayerDisplayName(playerWithPuck));
                        priority = CommentaryPriority.Medium;
                    }
                    else if (previousZone == "Neutral" && currentZone != "Neutral" && currentZone != defensiveZone)
                    {
                        comment = $"{GetPlayerDisplayName(playerWithPuck)} {string.Format(zoneEntryPhrases[random.Next(zoneEntryPhrases.Count)], "", "blue line")}";
                        priority = CommentaryPriority.Medium;
                    }
                    else if (previousZone != "Neutral" && currentZone != "Neutral" && previousZone != currentZone)
                    {
                         comment = $"{GetPlayerDisplayName(playerWithPuck)} {string.Format(zoneEntryPhrases[random.Next(zoneEntryPhrases.Count)], "", "center line")}";
                         priority = CommentaryPriority.Medium;
                    }
                    if(comment != null) EnqueueCommentary(comment, priority);
                }
                else if (Mathf.Abs(playerWithPuck.transform.position.x) > 20f)
                {
                    if (boardBattleStartTime == 0f) { boardBattleStartTime = Time.time; }
                    else if (!isAnnouncingBoardBattle && Time.time - boardBattleStartTime > boardBattleTimeThreshold)
                    {
                        comment = boardBattlePhrases[random.Next(boardBattlePhrases.Count)];
                        EnqueueCommentary(comment, CommentaryPriority.Low);
                        isAnnouncingBoardBattle = true;
                    }
                }
                else if (!hasMadeAnnouncementThisPossession && Time.time - possessionStartTime > minPossessionTimeForAnnouncement)
                {
                    string phrase = possessionPhrases[random.Next(possessionPhrases.Count)];
                    if (phrase.Contains("{1}"))
                    {
                        string teamName = playerWithPuck.Team.Value == PlayerTeam.Blue ? "Blue" : "Red";
                        comment = string.Format(phrase, GetPlayerDisplayName(playerWithPuck), teamName);
                    }
                    else
                    {
                        comment = string.Format(phrase, GetPlayerDisplayName(playerWithPuck));
                    }
                    EnqueueCommentary(comment, CommentaryPriority.Low);
                    lastAnnouncedPlayerId = currentPlayerId;
                    hasMadeAnnouncementThisPossession = true; // Set here to prevent spamming possession calls
                }
            }

            if (playerWithPuck == null || Mathf.Abs(playerWithPuck.transform.position.x) < 20f) { boardBattleStartTime = 0f; isAnnouncingBoardBattle = false; }
            
            // --- STATE UPDATE LOGIC (at the end of the frame) ---
            if (playerWithPuck != null && (wasPuckFreeInLastFrame || (currentPlayerId != lastPlayerId)))
            {
                possessionStartTime = Time.time;
                hasMadeAnnouncementThisPossession = false;
            }
            else if (playerWithPuck == null && !wasPuckFreeInLastFrame)
            {
                lastPossessionChangeTime = Time.time;
            }

            if (playerWithPuck != null && currentPlayerId != lastPlayerId)
            {
                lastPlayerWithPuck = playerWithPuck;
            }

            if (lastPlayerWithPuck != null)
            {
                lastPlayerWithPuckTeam = lastPlayerWithPuck.Team.Value;
            }

            wasPuckFreeInLastFrame = (playerWithPuck == null);
        }

        private static void ProcessCommentaryQueue()
        {
            if (commentaryCooldown > 0)
            {
                commentaryCooldown -= Time.fixedDeltaTime;
            }

            lock (commentaryQueue)
            {
                if (commentaryQueue.Count > 0)
                {
                    var nextEvent = commentaryQueue.Peek();
                    
                    bool canOverride = (nextEvent.Priority > lastBroadcastPriority && nextEvent.Priority > CommentaryPriority.Low);

                    if (commentaryCooldown <= 0 || canOverride)
                    {
                        var eventToBroadcast = commentaryQueue.Dequeue();
                        Broadcast(eventToBroadcast.Message, eventToBroadcast.Priority);
                    }
                }
            }
        }


        private static void Broadcast(string message, CommentaryPriority priority = CommentaryPriority.Low)
        {
            if (string.IsNullOrEmpty(message) || message == lastBroadcastMessage) return;
            AnnouncerLogger.Log($"BROADCAST: {message}");
            if (NetworkManager.Singleton?.IsClient != true) return;

            if (BroadcastToChat) {
                if(UIChat.Instance != null) UIChat.Instance.AddChatMessage(message);
            }
            else { 
                if(UIToastManager.Instance != null) UIToastManager.Instance.ShowToast("announcer_commentary", message, 3f); 
            }

            lastBroadcastMessage = message;
            commentaryCooldown = CooldownDurations[priority];
            lastBroadcastPriority = priority;
            if (priority > CommentaryPriority.Low) {
                 hasMadeAnnouncementThisPossession = true;
            }
        }

        private static void ResetShotState()
        {
            isPuckTravelingAfterShot = false;
            isOffNetShot = false;
            potentialShooter = null;
            potentialSaver = null;
            shotTime = 0f;
        }

        private static void ResetPlayState()
        {
            ResetShotState();
            lastPlayerWithPuck = null;
            lastAnnouncedPlayerId = -1;
            isWaitingForFaceoffWin = false;
            wasPuckFreeInLastFrame = true;
            boardBattleStartTime = 0f;
            isAnnouncingBoardBattle = false;
            hasMadeAnnouncementThisPossession = false;
            lastPlayerWithPuckTeam = PlayerTeam.None;
            lastBroadcastMessage = "";
            lastSogCounts.Clear();
            lastBlockCounts.Clear();
            lastSaveCounts.Clear();
            lastPassCounts.Clear();
        }

        // --- Harmony Patches ---

        [HarmonyPatch(typeof(Puck), "OnCollisionEnter")]
        public class Puck_OnCollisionEnter_Patch
        {
            [HarmonyPostfix]
            public static void Postfix(Collision collision)
            {
                var stick = collision.gameObject.GetComponent<Stick>();
                if (stick != null && stick.Player != null)
                {
                    lastPuckTouchTime[stick.Player.GetInstanceID()] = Time.time;
                }
            }
        }

        [HarmonyPatch(typeof(Puck), "FixedUpdate")]
        public class Puck_FixedUpdate_Patch
        {
            public static void Postfix(Puck __instance)
            {
                // Process any actions that were enqueued from other threads
                lock(mainThreadActions)
                {
                    while(mainThreadActions.Count > 0)
                    {
                        mainThreadActions.Dequeue().Invoke();
                    }
                }

                ProcessCommentaryQueue();
                
                if (!isDetectionMethodSet && NetworkManager.Singleton != null)
                {
                    if (NetworkManager.Singleton.IsClient && !NetworkManager.Singleton.IsServer)
                    {
                        if (!useLogFileDetection) 
                        {
                            LogFileMonitor.Initialize();
                            LogFileMonitor.OnStatFound += HandleStatFound;
                            useLogFileDetection = true;
                            AnnouncerLogger.Log("Multiplayer Client detected. Using Log File for accurate stat detection.");
                        }
                    }
                    else
                    {
                        if (useLogFileDetection)
                        {
                            LogFileMonitor.OnStatFound -= HandleStatFound;
                            LogFileMonitor.Stop();
                        }
                        useLogFileDetection = false;
                        AnnouncerLogger.Log("Host or local game detected. Using internal physics for stat detection.");
                    }
                    isDetectionMethodSet = true;
                }


                if (__instance != null && puckTargetingSystem == null)
                {
                    puckTargetingSystem = __instance.gameObject.GetComponent<PuckTargetingSystem>() ?? __instance.gameObject.AddComponent<PuckTargetingSystem>();
                }

                if (GameManager.Instance?.GameState != null)
                {
                    GameState currentState = GameManager.Instance.GameState.Value;

                    if (isFirstCheck) { lastKnownGameState = currentState; isFirstCheck = false; }
                    else
                    {
                        if (currentState.Phase != lastKnownGameState.Phase)
                        {
                            AnnouncerLogger.Log($"Game phase changed from {lastKnownGameState.Phase} to {currentState.Phase}");
                            if (currentState.Phase == GamePhase.FaceOff)
                            {
                                isDetectionMethodSet = false;
                                if (useLogFileDetection) {
                                    LogFileMonitor.Stop();
                                    useLogFileDetection = false;
                                }
                                ResetPlayState();
                                lastPuckTouchTime.Clear();
                                isWaitingForFaceoffWin = true;
                            }
                        }

                        if (currentState.RedScore > lastKnownGameState.RedScore || currentState.BlueScore > lastKnownGameState.BlueScore)
                        {
                            ResetPlayState();
                            string scorer = File.Exists(goalScorerFile) ? File.ReadAllText(goalScorerFile).Trim() : "";
                            string assister = File.Exists(assistPlayerFile) ? File.ReadAllText(assistPlayerFile).Trim() : "";
                            string secondAssister = File.Exists(secondAssistPlayerFile) ? File.ReadAllText(secondAssistPlayerFile).Trim() : "";

                            string teamScored = (currentState.RedScore > lastKnownGameState.RedScore) ? "Red" : "Blue";
                            string goalComment = $"GOAL for the {teamScored} team! The score is now {currentState.RedScore} to {currentState.BlueScore}.";

                            if (!string.IsNullOrEmpty(scorer))
                            {
                                goalComment = $"GOAL! Scored by {scorer}. The score is {currentState.RedScore} to {currentState.BlueScore}.";
                                if (!string.IsNullOrEmpty(assister))
                                {
                                    goalComment += $" Assist to {assister}";
                                    if (!string.IsNullOrEmpty(secondAssister)) goalComment += $", with the secondary from {secondAssister}.";
                                    else goalComment += ".";
                                }
                            }

                            Broadcast(goalComment, CommentaryPriority.High);
                        }

                        lastKnownGameState = currentState;
                    }
                }

                try { RunCommentary(__instance); }
                catch (Exception e) { AnnouncerLogger.Log($"Error in RunCommentary: {e}"); }
                finally { lastPuckPosition = __instance.transform.position; }
            }
        }
    }
}
